from setuptools import setup, find_packages

setup(
    name="probing_norms",
    version="0.0.1",
    url="https://github.com/danoneata/probing-norms",
    author="Dan Oneață",
    author_email="dan.oneata@gmail.com",
    description="Understanding deep learning models by probing feature norms",
    packages=find_packages(),
    # package_data={"probing_norms": ["data/*"]},
    install_requires=[
        "black",
        "click",
        "streamlit",
        "ruff",
        "tqdm",
        "transformers",
        "timm",
        "scikit-learn",
        "toolz",
        "h5py",
        "fasttext",
        "adjustText",
        "seaborn",
        "numpy",
        "pandas",
        "importlib_resources",
        "parsy",
        "pillow",
        "openpyxl",
        "open_clip_torch",
        "qwen-vl-utils",
        "inflect",
        "umap-learn",
    ],
)
